FROM node:20-alpine AS builder
WORKDIR /app
ARG VITE_ORDER_SERVICE_URL=http://mycluster.local.com/order
ENV VITE_ORDER_SERVICE_URL=$VITE_ORDER_SERVICE_URL
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY deployment/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
